### ISSUE TITLE
clReleaseProgram warning

### ISSUE THREAD

**Issue by definelicht** [definelicht/sdaccel_memory_benchmark#4]
Some versions of the runtime prints the below warnings:

```
WARNING: Profiling may contain incomplete information. Please call clReleaseProgram() from your host code.
```

This needs to be reproduced. Most likely, a call to `clReleaseProgram()` should be added to the destructor of the kernel class.

**Comment by sinatv52** [comment]
Hi @definelicht 

for an other project i am facing similar error, as this issue is closed a long time ago may you tell me what was the problem and solution?
thanks.

**Comment by definelicht** [comment]
Hi @sinatv52, you can check the linked commit: 4bbce37
It was just missing cleanup calls.

**Comment by sinatv52** [comment]
I wanted to run a project on github. i got this error. also i think sth in the host code is not released. but i checked main opencl objects (like program,kernels, context,commandqueue)but i did not find any object that was not released. it is some ]how complicated to find which object is not released due to the the Multiplicity of opencl objects like buffers.

However, thanks for your reply, sir.

**Comment by definelicht** [comment]
Perhaps it's an issue of ordering? For example releasing the context before releasing the program?

**Comment by sinatv52** [comment]
due to some objects are dependent of the others, it can be the issue. I searched the web and opencl website and didn't find any documentation about it. maybe you tell me a reference about that?

this is the order of releasing:
        free(a1)
	clReleaseMemObject(d_output);
	clReleaseMemObject(d_filter);

	clReleaseKernel(standard_conv);
	clReleaseKernel(depthwise_conv);
	clReleaseKernel(pointwise_conv);
	clReleaseProgram(program);

	clReleaseCommandQueue(commands);
	clReleaseContext(context);

**Comment by sinatv52** [comment]
by changing the host code to c++ wrapper which with that there is no need to release object, i could run my code. it releases those automaticaclly.
